Repository pagopa/pagopa-qi-jsm-management-function, pull requests merged in 2023-09, with the labels that each got.

#5 Update identity openapi info
  .github/workflows/code_review.yml
  .github/workflows/deploy_with_github_runner.yml
  .identity/99_variables.tf
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/qi/jsmmanagement/Example.java
  src/main/java/it/gov/pagopa/qi/jsmmanagement/Info.java
  src/main/java/it/gov/pagopa/qi/jsmmanagement/model/AppInfo.java
  src/main/resources/schemas/events/v1/alert.json
  src/test/java/it/gov/pagopa/qi/jsmmanagement/ExampleTest.java
  src/test/java/it/gov/pagopa/qi/jsmmanagement/InfoTest.java
  src/test/resources/META-INF/maven/it.gov.pagopa.qijsmmanagement/qi-jsm-management-function/pom.properties
Labels: bug, enhancement

#6 chore(runtime): update java runtime to 17
  .github/workflows/update_code.yml
  .java-version
  Dockerfile
  docker/.env
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small

#7 feat: adding function with loggers PQI-42
  .github/workflows/code_review.yml
  .github/workflows/deploy_with_github_runner.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/qi/jsmmanagement/JsmIngestion.java
Labels: enhancement, size/small

#8 fix min replicas
  helm/values-uat.yaml
Labels: size/small

#9 Pqi 42 jira integration
  README.md
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  local.settings.json.example
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/qi/jsmmanagement/JsmIngestion.java
  src/main/java/it/pagopa/qi/jsmmanagement/Info.java
  src/main/java/it/pagopa/qi/jsmmanagement/JsmIngestion.java
  src/main/java/it/pagopa/qi/jsmmanagement/config/JiraRestClientConfig.java
  src/main/java/it/pagopa/qi/jsmmanagement/exceptions/AlertParsingException.java
  src/main/java/it/pagopa/qi/jsmmanagement/exceptions/JiraTicketCreationException.java
  src/main/java/it/pagopa/qi/jsmmanagement/model/AppInfo.java
  src/test/java/it/pagopa/qi/jsmmanagement/InfoTest.java
  src/test/java/it/pagopa/qi/jsmmanagement/JsmIngestionTest.java
Labels: size/large
